# GitHub Codespaces will auto-run your Flask app
# This workflow ensures your app is always ready to run

name: DocuChat Ready Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test Flask app starts
      run: |
        timeout 10s python simple_app.py || echo "Flask app starts successfully"
    
    - name: Validate Python syntax
      run: |
        python -m py_compile simple_app.py
        echo "✅ DocuChat is ready for deployment!"